<?php

use App\Http\Controllers\AfterSalesController;
use App\Http\Controllers\AttractionController;
use App\Http\Controllers\AvailabilityController;
use App\Http\Controllers\ClaimController;
use App\Http\Controllers\CurrencyController;
use App\Http\Controllers\DashboardBookingController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DocumentDownloadController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InvoiceDownloadController;
use App\Http\Controllers\LegalController;
use App\Http\Controllers\ListingController;
use App\Http\Controllers\ListingsPartnerHandbookPdfController;
use App\Http\Controllers\MarketingMaterialDownloadController;
use App\Http\Controllers\PartnerApiGuideController;
use App\Http\Controllers\PaymentBridgeReturnController;
use App\Http\Controllers\PaymentCheckoutController;
use App\Http\Controllers\PaymentFormBridgeController;
use App\Http\Controllers\PaymentReturnController;
use App\Http\Controllers\SavedPlanController;
use App\Http\Controllers\SiteTermsController;
use App\Http\Controllers\ThumbnailController;
use App\Http\Controllers\TripCardImageController;
use App\Http\Controllers\TripController;
use App\Http\Controllers\WebsiteTermsController;
use App\Http\Controllers\WorkbookDownloadController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

// The booking subdomain is the lodge-facing product's own front door, so its
// root is the panel and not the travel site. Registered before everything
// else because Laravel matches routes in order, and '/' below would otherwise
// answer first — a host constraint does not make a route more specific, only
// narrower. Does nothing at all until config('booking.panel_domain') is set,
// which is why local development and CI never notice it.
if (filled(config('booking.panel_domain'))) {
    Route::domain((string) config('booking.panel_domain'))
        ->get('/', fn () => redirect('/partner'))
        ->name('booking.home');
}

Route::get('/', HomeController::class)->name('home');

// Placeholder — needs real content from NamibWay's own legal review before this
// is relied on for actual publish consent. See the publish confirmation modal,
// which links here.
Route::get('terms', fn () => Inertia::render('Terms'))->name('terms');

// The legal notice / imprint, plus the photo credits. Linked from the footer
// of every page, because a legal notice nobody can find from the page they
// are on is not one.
Route::get('legal', LegalController::class)->name('legal');

Route::get('partner-api-guide.pdf', PartnerApiGuideController::class)->name('partner-api-guide');

Route::get('admin/listings-partner-handbook.pdf', ListingsPartnerHandbookPdfController::class)
    ->middleware('auth')
    ->name('listings-partner-handbook-pdf');

// Flyer PDFs listed on the admin panel's "Marketing material" page. The item and
// variant are resolved against config/marketing.php, never against the filesystem.
Route::get('admin/marketing-material/{item}/{variant}', MarketingMaterialDownloadController::class)
    ->middleware('auth')
    ->name('marketing-material.download');

// Workbooks generated by the admin panel (listing export/template/import report).
// The signed link is minted by App\Filament\Support\WorkbookDownload.
Route::get('admin/workbooks/{token}', WorkbookDownloadController::class)
    ->middleware(['auth', 'signed'])
    ->name('workbooks.download');

// Files filed under Documents in the admin panel. They sit on the private disk,
// so this route is the only way to them and its admin check is the access rule.
Route::get('admin/documents/{document}/file', DocumentDownloadController::class)
    ->middleware('auth')
    ->name('documents.download');

/*
 * Paying a booking.
 *
 * No authentication, deliberately: the reference in the URL is a long random
 * string and is what identifies the attempt, the same arrangement the saved-plan
 * tokens use. A payment link mailed to a guest cannot demand they hold an
 * account — booking is behind one, paying an already-issued request is not.
 *
 * The checkout page belongs to the demo provider and 404s for anything else; a
 * real gateway hosts its own.
 */
Route::get('pay/{intent}', [PaymentCheckoutController::class, 'show'])->name('payments.checkout');
Route::post('pay/{intent}', [PaymentCheckoutController::class, 'decide'])->name('payments.decide');
Route::get('pay/{intent}/done', PaymentReturnController::class)->name('payments.return');
// Form-POST bridge routes for gateways that redirect via a browser-submitted form
// rather than a plain GET. The return route is CSRF-exempt (bootstrap/app.php)
// because the gateway's redirect is a cross-domain POST with no session.
Route::get('pay/{intent}/go', PaymentFormBridgeController::class)->name('payments.paygate.redirect');
Route::post('pay/{intent}/paygate-done', PaymentBridgeReturnController::class)->name('payments.paygate.return');

// Invoices are rendered on demand from their frozen snapshot rather than
// stored, so this route is the only way to the document and its check is the
// access rule — see InvoiceDownloadController.
Route::get('invoices/{invoice}/pdf', InvoiceDownloadController::class)
    ->middleware('auth')
    ->name('invoices.pdf');

Route::post('currency', [CurrencyController::class, 'update'])
    ->middleware('throttle:30,1')
    ->name('currency.update');

// Width-limited copies of catalog photos, made on first request (see
// ThumbnailController). `.*` because the tail is a bucket key with slashes in
// it. Throttled generously: a single page legitimately asks for a couple of
// dozen of these at once, and only a first-ever view reaches PHP at all — once
// the variant exists the response is a cacheable redirect.
Route::get('thumbs/{width}/{path}', ThumbnailController::class)
    ->where('path', '.*')
    ->middleware('throttle:240,1')
    ->name('thumbs.show');

Route::get('listings/search', [ListingController::class, 'search'])->name('listings.search');

// Things to see, beside the things to book: the trip plan's activity picker
// offers both, and an attraction has a detail modal of its own because it has
// no listing page to open.
Route::get('attractions/search', [AttractionController::class, 'search'])->name('attractions.search');
Route::get('attractions/{slug}', [AttractionController::class, 'show'])->name('attractions.show');
Route::get('listings/{listing:slug}/preview', [ListingController::class, 'preview'])->name('listings.preview');
// Real room types + remaining units for a stay, for the trip plan's room
// picker. Open like the rest of browsing — booking one is what needs an
// account.
Route::get('listings/{listing:slug}/room-types', [ListingController::class, 'roomTypes'])
    ->middleware('throttle:60,1')
    ->name('listings.room-types');
// Unified availability for all verticals (accommodation, activity, vehicle).
// `check_out` is optional — slot-based units (activities) query a single date.
// See AvailabilityController and BOOKING_BEYOND_ROOMS.md §7.1.
Route::get('availability', AvailabilityController::class)
    ->middleware('throttle:60,1')
    ->name('availability');
Route::get('listings/{listing:slug}', [ListingController::class, 'show'])->name('listings.show');
Route::post('listings/{listing:slug}/publish', [ListingController::class, 'publish'])->name('listings.publish');
Route::post('listings/{listing:slug}/approve-photos', [ListingController::class, 'approvePhotos'])->name('listings.approve-photos');
Route::get('listings/{listing:slug}/edit', [ListingController::class, 'edit'])->name('listings.edit');
Route::put('listings/{listing:slug}', [ListingController::class, 'update'])->name('listings.update');
Route::post('listings/{listing:slug}/enrich', [ListingController::class, 'enrich'])->name('listings.enrich');

Route::post('trip/save', [SavedPlanController::class, 'store'])
    ->middleware('throttle:20,1')
    ->name('trip.save');

Route::get('trip/{token}', [SavedPlanController::class, 'show'])
    ->name('trip.show');

Route::get('trip/{token}/pdf', [SavedPlanController::class, 'pdf'])
    ->middleware('throttle:10,1')
    ->name('trip.pdf');

// The og:image of the page above. Fetched by link unfurlers with no session,
// so it can't sit behind auth — see TripCardImageController.
Route::get('trip/{token}/card.png', TripCardImageController::class)
    ->middleware('throttle:60,1')
    ->name('trip.card');
// Sending an inquiry is a booking request, and booking needs an account (see
// CLAUDE.md's account line) — so both of these sit behind `auth`. Browsing,
// planning and sharing a plan stay open; only the commitment step doesn't.
Route::post('listings/{listing:slug}/inquiries', [ListingController::class, 'storeInquiry'])
    ->middleware(['auth', 'throttle:10,1'])
    ->name('listings.inquiries.store');

Route::post('inquiries/batch', [ListingController::class, 'storeBatchInquiry'])
    ->middleware(['auth', 'throttle:10,1'])
    ->name('inquiries.batch.store');

Route::post('listings/{listing:slug}/reviews', [ListingController::class, 'storeReview'])
    ->middleware('throttle:10,1')
    ->name('listings.reviews.store');

Route::post('trips', [TripController::class, 'store'])->middleware(['auth', 'throttle:5,1'])->name('trips.store');
Route::get('trips/{trip}/inquiries', [TripController::class, 'inquiries'])->middleware(['auth', 'throttle:30,1'])->name('trips.inquiries');

Route::post('support', [AfterSalesController::class, 'support'])->middleware('throttle:5,1')->name('support.store');
Route::post('feedback', [AfterSalesController::class, 'feedback'])->middleware('throttle:5,1')->name('feedback.store');

Route::get('claim/{token}', [ClaimController::class, 'show'])->name('claim.show');
Route::post('claim/{token}', [ClaimController::class, 'store'])->middleware('auth')->name('claim.store');
Route::get('claim/{token}/decline', [ClaimController::class, 'declineShow'])->name('claim.decline.show');
Route::post('claim/{token}/decline', [ClaimController::class, 'decline'])->name('claim.decline');

// Store intended URL in session so Fortify redirects back after login
Route::get('login/start', function (Request $request) {
    $url = $request->query('redirect', '');

    if (is_string($url) && str_starts_with($url, '/')) {
        $request->session()->put('url.intended', url($url));
    }

    return redirect()->route('login');
})->middleware('guest')->name('login.start');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('dashboard', DashboardController::class)->name('dashboard');
    Route::post('dashboard/bookings/{inquiry}/confirm', [DashboardBookingController::class, 'confirm'])
        ->name('dashboard.bookings.confirm');
    Route::post('dashboard/bookings/{inquiry}/decline', [DashboardBookingController::class, 'decline'])
        ->name('dashboard.bookings.decline');
});

/*
| Our own terms for the website product, linked from the foot of every customer
| site. A plain page rather than an Inertia one: those readers arrive from a
| host that ships none of the travel platform.
*/
Route::get('website-terms', WebsiteTermsController::class)->name('website.terms');

/*
| The business confirming its own website, from a link in an email. Two routes
| on one URI: a signature covers the address and not the method, so the page the
| GET renders posts its form straight back to the address it was reached at. The
| GET only shows — a mail client that prefetches links must not be able to
| publish somebody's website by opening the message.
*/
Route::get('sites/{site}/confirm', [SiteTermsController::class, 'show'])
    ->name('sites.terms.confirm')
    ->middleware('signed');

Route::post('sites/{site}/confirm', [SiteTermsController::class, 'confirm'])
    ->name('sites.terms.confirm.send')
    ->middleware('signed');

require __DIR__.'/settings.php';
require __DIR__.'/auth.php';
require __DIR__.'/kaia.php';
require __DIR__.'/partner.php';
